server:
  port: 10001

mybatis:
  mapperLocations: classpath*:mapper/*.xm

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          username: jcpt
          password: '@na#V!968@dev'
          url: jdbc:mysql://10.16.32.177:3306/hl_master?useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=PRC
        slave_1:
          url: jdbc:mysql://10.16.32.177:3306/hl_slave1?useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=PRC
          username: root
          password: 123456
        #        slave_2:
        #          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
        #          username: ENC(xxxxx)
        #          password: ENC(xxxxx)
        #          driver-class-name: com.mysql.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
  main:
    banner-mode: off
  application:
    name: custom

mqtt:
  url: tcp://localhost:1883
  username: admin
  password: public
  keep-alive: 30
  connection-timeout: 3000
  producerClientId:  test-producer
  producerQos: 1
  consumerClientId: test-consumer
  consumerQos: 1
  deafultTopic : test



